### ISSUE TITLE
home :: banner :: btn

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-pavlova#20]
el texto deberia ir en 1 linea, ahorita se muestra en dos
<img width="268" alt="screen shot 2016-05-12 at 6 04 01 pm" src="https://cloud.githubusercontent.com/assets/7799215/15233153/06b80f2a-186c-11e6-9bba-0b7bdfcbfc88.png">

**Comment by ale-romo** [comment]
fixed
