### ISSUE TITLE
home :: nuestra escuela :: img dimension

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-pavlova#22]
en el diseno marcan 450 x 290, ahorita tenemos otra dimension, se puede ajustar un poco?
si se puede bien, si no asi se va
<img width="860" alt="screen shot 2016-05-12 at 6 09 50 pm" src="https://cloud.githubusercontent.com/assets/7799215/15233245/d5333c4e-186c-11e6-9d02-38f99d99bdd1.png">

**Comment by ale-romo** [comment]
Así se va. hay una discrepancia de 7px, y es descuadrar y modificar el carousel bastante.
