### ISSUE TITLE
escuela ::  nuestra escuela :: indicadores

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-pavlova#26]
en el diseno van pegados a la izquierda y con mas espacio entre ellos
<img width="300" alt="screen shot 2016-05-12 at 6 41 50 pm" src="https://cloud.githubusercontent.com/assets/7799215/15233809/44fda20e-1871-11e6-85cb-b80ab95baa50.png">

**Comment by ale-romo** [comment]
done
