### ISSUE TITLE
escuela ::  nuestra escuela :: btn

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-pavlova#27]
la fecha deberia apuntar a la derecha, ahorita esta para abajo,
por otra parte este btn en el diseno esta mas ancho y menos alto, puedes ver que pex? si se puede hacer algo chido

<img width="265" alt="screen shot 2016-05-12 at 6 42 45 pm" src="https://cloud.githubusercontent.com/assets/7799215/15233857/83f25450-1871-11e6-84e1-104093977ca8.png">

**Comment by ale-romo** [comment]
listo
