### ISSUE TITLE
escuela :: pas de chat :: indicadores

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-pavlova#28]
el slider si tiene los indicadores a nivel de codigo, pero no se ven supongo porque son blancos y el fondo esta blanco, asi que meterle su border, y supongo tambien van a requerir mas espacio entre ellos y alineados a la izquierda

<img width="524" alt="screen shot 2016-05-12 at 6 45 14 pm" src="https://cloud.githubusercontent.com/assets/7799215/15233885/d12b33cc-1871-11e6-8140-8f31d29c131a.png">

**Comment by ale-romo** [comment]
medio ya, nomás falta que el componente reciva style.active
