### ISSUE TITLE
escuela ::  testimoniales :: ancho

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-pavlova#30]
podemos meterlo el "contenido" en un

```
<row>
<col-8> o <col-10>
```

para que quede menos ancho como en el diseno?
<img width="1020" alt="screen shot 2016-05-12 at 6 53 13 pm" src="https://cloud.githubusercontent.com/assets/7799215/15234010/ded1dcdc-1872-11e6-9d28-c0c54a467347.png">

**Comment by ale-romo** [comment]
que es un 'o'

**Comment by garciadiazjaime** [comment]
ya lo ajuste, quise decir col-X, x < 12
