### ISSUE TITLE
general :: header :: linea rara

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-pavlova#35]
no se si a ti te pase, pero hay como una linea punteada en el header, como la pendiente, tu lo ves?
(al hacer grande la foto se ve)

<img width="1439" alt="screen shot 2016-05-12 at 8 00 30 pm" src="https://cloud.githubusercontent.com/assets/7799215/15234920/805470e8-187c-11e6-801c-e82be0222e6c.png">

**Comment by ale-romo** [comment]
listo
