### ISSUE TITLE
general :: header :: imgs

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-pavlova#36]
en general, en todas las secciones la primer img sale algo mochada, deberia haber mas espacio entre menu y comienzo de "image" que es donde sale el mon@

inicio
<img width="1133" alt="screen shot 2016-05-12 at 8 04 07 pm" src="https://cloud.githubusercontent.com/assets/7799215/15234939/b2b3d60a-187c-11e6-83d3-69c636a71752.png">

escuela:
<img width="1132" alt="screen shot 2016-05-12 at 8 04 41 pm" src="https://cloud.githubusercontent.com/assets/7799215/15234950/ca0edeee-187c-11e6-8db8-d802763641e4.png">

clases
<img width="1346" alt="screen shot 2016-05-12 at 8 03 36 pm" src="https://cloud.githubusercontent.com/assets/7799215/15234937/aa4fe7a6-187c-11e6-9235-f8a508034fee.png">

**Comment by ale-romo** [comment]
![screen shot 2016-05-12 at 6 14 06 pm](https://cloud.githubusercontent.com/assets/5589437/15235119/5d67648c-186d-11e6-9ed8-eb400ca39127.png)
![screen shot 2016-05-12 at 6 14 01 pm](https://cloud.githubusercontent.com/assets/5589437/15235120/5d707c52-186d-11e6-9c93-418ede7032eb.png)
![screen shot 2016-05-12 at 6 13 54 pm](https://cloud.githubusercontent.com/assets/5589437/15235121/5d70b924-186d-11e6-9300-539495485ac8.png)

En general eso ya está arreglado, revisa que si le hayas hecho update a todo
