### ISSUE TITLE
rd :: inicio :: nuestra escuela

### ISSUE THREAD

**Issue by garciadiazjaime** [garciadiazjaime/website-pavlova#39]
texto en otras secciones tiene un padding, por alguna razon en este bloque esta completamente pegado a las orillas
<img width="463" alt="screen shot 2016-05-12 at 8 14 12 pm" src="https://cloud.githubusercontent.com/assets/7799215/15235130/341f5312-187e-11e6-8512-f6ba7ae7ca0b.png">

**Comment by ale-romo** [comment]
el texto me sale igual que en las demás secciones.

**Comment by ale-romo** [comment]
![screen shot 2016-05-12 at 6 21 25 pm](https://cloud.githubusercontent.com/assets/5589437/15235233/64359044-186e-11e6-822d-4e30b8f27aba.png)
